### ISSUE TITLE
[FR] add colon or dash in result divider for POST Game view

### ISSUE THREAD

**Issue by schmierlappe** [vasqued2/ha-teamtracker-card#114]
Is it possible to add a colon or dash into the divider to have more regular Result view especially for Soccer in the POST Game View?

like this

![image](https://github.com/user-attachments/assets/1d9c8ef3-f379-418d-8061-ed8b21e69a55)

**Comment by vasqued2** [comment]
Depending on the sport, scores can be negative or be positions so the '-' doesn't look right for them.  

The card is designed to be fully compatible with [card-mod](https://github.com/thomasloven/lovelace-card-mod) and you should be able to accomplish what you are looking for with it.  That's one on the reasons I made it compatible is so anyone can modify it in any way they want without changes to the card itself.  If you have any problems doing what you want to do with card-mod, let me know.

Here's an example:

```
type: custom:teamtracker-card
entity: sensor.zui_tt_atp
show_league: true
card_mod:
  style: |
    .divider::after {
        content: "-\00a0\00a0\00a0";
        display: inline-block; 
    }
```

**Comment by vasqued2** [comment]
Assumed this worked and closing
