### ISSUE TITLE
NHL Detroit not working

### ISSUE THREAD

**Issue by Patte22** [vasqued2/ha-teamtracker-card#116]
No matter what I try, I cannot display information for the Detroit Red Wings (NHL/DET). I have tested other teams in NHL and also Detroit Lions (NFL/DET) without problem.

**Comment by vasqued2** [comment]
Looks like the RWs don’t have a game until 9/25.  Not home so can’t check, but my guess is the API is only returning games through the 21st or so.  What date does the card or api_message say the games are through?

Of course it wouldn’t surprise me if the sensor has a bias against Michigan teams.

**Comment by vasqued2** [comment]
As expected, DET is working now that it is close up enough to the game date.
