### ISSUE TITLE
Time in 24H format

### ISSUE THREAD

**Issue by MartinJohannesNilsen** [vasqued2/ha-teamtracker-card#12]
Would be nice to have a boolean for 24h or 12h format

**Comment by vasqued2** [comment]
Right now, the time and date format is based on the language of your frontend.  

For example, pick English and you will get 12 hour format.  Pick English (GB) and it will use 24 hour format.  I'll leave this open and research what it would take to allow the Time Format selected in the frontend to override the format based on the selected language.

**Comment by vasqued2** [comment]
v0.4.2 will use the Time Format from your User Profile, so you can override the language-based default if desired.
