### ISSUE TITLE
Card events bug

### ISSUE THREAD

**Issue by kevvar** [vasqued2/ha-teamtracker-card#125]
Hi

I have a situation that I'm not sure if I should consider a bug. When I follow events like soccer, the events and minutes appear above shots on target. But now I'm following the NHL, and I can't see that information. Is this a bug or normal behavior?
![Screenshot_20241014-213013_Home Assistant](https://github.com/user-attachments/assets/599818e6-92be-4ac8-9c22-bf3ccd100ae8)

**Comment by vasqued2** [comment]
The existence of the last play varies from sport to sport and even language by language.  In this case, the API isn't returning a Spanish translation even though it provides one in English.  Nothing I can do about it as the sensor is just a pass through for what the API returns.  If you wanted, you could override the API language to English, but that would impact all the values returned by the API.
![image](https://github.com/user-attachments/assets/2f4353a5-adb7-47c3-8208-8453ddc59891)

**Comment by kevvar** [comment]
Oh! Got it, I'll override the api language. Thanks a lot!!

**Comment by kevvar** [comment]
Hey man, @vasqued2, is it possible to see any kind of special identifier for teams during power play situations in the NHL

**Comment by vasqued2** [comment]
Sorry.  I've looked for one many times and the API doesn't return one.

**Comment by kevvar** [comment]
Oh bad news. Thanks friend!
