### ISSUE TITLE
Follow users time zone preference

### ISSUE THREAD

**Issue by preischeld** [vasqued2/ha-teamtracker-card#130]
As a user, I would love for the card to follow my home assistant users time zone preference (either server time or local time), so that I can use these cards in a browser that hardcodes the time zone.

scenario:
I have some cards on a home assistant dashboard that runs on the browser in a Tesla. Tesla has hard coded the browser to always be Pacific time, but I am not in pacific time. The card always shows the times in pacific time no matter what my user setting for time zone is.

Setting the users time to server time should get around this, but I believe the card may be following the browser time, so it always shows pacific time.

**Comment by vasqued2** [comment]
Thanks.  I missed it when this option was added.  It should work correctly in v0.14.14.  Lmk if you have issues after upgrading.

**Comment by preischeld** [comment]
Just tried it out and it worked perfectly. Thank you very much!
