### ISSUE TITLE
Custom element doesn't exist: teamtracker-card.

### ISSUE THREAD

**Issue by coleburg** [vasqued2/ha-teamtracker-card#20]
Updated to 0.5.1 and now receiving

Custom element doesn't exist: teamtracker-card.

even though I can see it installed, anyone else with this?

**Comment by coleburg** [comment]
seems to have gone now :-/

**Comment by JonnyFiat** [comment]
I've actually had this occurring to me. Do you know how it resolved?
![image](https://user-images.githubusercontent.com/93795449/203659949-a6d633ae-df2a-4a42-abb2-86afc0ccc17b.png)

**Comment by Brandon1212b** [comment]
Bump I am having the same issue. Is there any solution for this?
