### ISSUE TITLE
Team display in card

### ISSUE THREAD

**Issue by mrkcrc** [vasqued2/ha-teamtracker-card#22]
I love the card but I just realized the display order of the team in the card is inaccurate.  Granted I'm only using the cards for football currently but It seems to always list the team you are tracking first on the card instead of the 'Away' team in that matchup.  The display should always be Away team vs. (at) Home Team.  Not a big deal but just thought it was worth mentioning.

**Comment by vasqued2** [comment]
Good timing.  v0.5.2 that was released yesterday addresses this.  

If you would prefer that the Home team always be placed on the left or right side (different countries and sports have different standards so there is no universal order that works for everyone), you can now use the `home_side` option in the card configuration to do so.  Valid values are `left` and `right`.

If you don't use the `home_side` option, it will continue to function as it does today and put the team you are tracking first.

Try it and let me know if it works or you have any problems with it.

Example
```
  - type: custom:teamtracker-card
    entity: sensor.tt_test
    outline: true
    outline_color: lightgray
    show_league: true
    home_side: right
```

**Comment by mrkcrc** [comment]
Ah!  Excellent point and good solution.  Thx.
