### ISSUE TITLE
Feature Request - Add Tap Action 

### ISSUE THREAD

**Issue by ClaymoreTech4** [vasqued2/ha-teamtracker-card#25]
Add the ability to add tap action to the cards, I would add a URL to my favorite teams website.

**Comment by kicker10BOG** [comment]
I would like to second this. A tap action to view the entity and its attributes would be a nice improvement.

**Comment by vasqued2** [comment]
I am finally getting around to this.

Can you give me more specifics. Do you want to click on different components of the card to have different things happen? If so, what type of things? Links to other sites, HA actions, etc? Or do you want different things to happen on different actions like you describe? Give me examples of the actions.

I am leaning towards creating 3 hot spots. One on each team icon and one at the bottom. By default they will link to each team page and the game page on ESPN but will allow each url to be overwritten in the card config.

**Comment by vasqued2** [comment]
This feature was added in v0.14.0.  It requires v0.14.0 of the team tracker sensor as well.

**Comment by ClaymoreTech4** [comment]
Thank you
