### ISSUE TITLE
Can’t save card

### ISSUE THREAD

**Issue by ctankep23** [vasqued2/ha-teamtracker-card#26]
I just installed the integration through HACS and then the card. I’ve restarted HA and entered my league/team details according to the instructions. I’m trying to follow AIK in Swedish Allsvenskan, so I entered XXX and then set it up using “swe.1”.

I then create a manual card and enter the details. A nice preview shows up, but at the bottom of the card I see “Cancel” and where the save button should be it’s only a spinning circle that never stops and becomes the save button. I’ve taken away all the variables down to the bare two line necessities but no luck.

![61B4AC23-76E6-4411-AC42-511FF59ACF11](https://user-images.githubusercontent.com/63706053/205764267-69235ca8-d5db-41df-8a2c-55d3e9892a03.png)

**Comment by vasqued2** [comment]
I don't know.  Did you try to add it using a manual card?
