### ISSUE TITLE
For F1 card ?

### ISSUE THREAD

**Issue by schumi2309** [vasqued2/ha-teamtracker-card#28]
Hello,
Is there an example card for a Formula 1 race?
Either with the first 5, lap times, etc...

very thanks.

**Comment by vasqued2** [comment]
It uses the same format as the others.  If you are following a specific driver, it will show that driver and whoever is in first place.  If you use a wildcard, it will just show the top two drivers.

While the practice runs, qualifying, and races are underway, it will show a lap count in the Game Bar (where probability is displayed for football) and the scroll will display the top 10 drivers (where the last play is displayed for football).

The API does not return lap times or other information.

I considered creating a new leaderboard card for racing and golf but the API doesn't really return a lot of additional info other the current place, especially for races.

**Comment by schumi2309** [comment]
Ok, I see what you mean, but that's it. I would do with.
Thank you for all the info, and continue to develop the add-on, it's very good work. congratulations.
