### ISSUE TITLE
Team logos don't respect corner radius

### ISSUE THREAD

**Issue by m1ke-hub** [vasqued2/ha-teamtracker-card#30]
First of all, thanks a lot for this cool card and integration! I've been looking for something like that for ages.

I noticed that the big faded logos do not respect the corner-radius set in the theme, as seen in the screenshot below:

<img width="643" alt="Bildschirm­foto 2022-12-18 um 19 53 22" src="https://user-images.githubusercontent.com/57773976/208314428-0c3f5577-26e3-4eed-b18c-b1dc1dd67b42.png">

Would that somehow be possible to include?

Thanks in advance :)

**Comment by vasqued2** [comment]
I honestly never noticed.  Do you have any example cards that behave correctly?  If so, I can take a look and see how they are handling it.

**Comment by m1ke-hub** [comment]
The only card I currently use, that kind of has a similarity is the mini-media-player by kalkih - where the album cover can be compared to the logos. Maybe that helps?

**Comment by m1ke-hub** [comment]
I just tried some things in the inspector.. When I add _border-radius: var(--ha-card-border-radius);_ to div class="card" (see screenshot), it looks as expected.

![Bildschirm­foto 2022-12-20 um 18 26 51](https://user-images.githubusercontent.com/57773976/208729740-ddd66a8d-7103-4af5-811d-420fb03b5561.png)

**Comment by vasqued2** [comment]
Thanks!  I'll make the change.

**Comment by vasqued2** [comment]
What browser and theme are you using?  For some reason it's not picking up a value for var(--ha-card-border-radius).  Or maybe I'm inserting it in the wrong spot.  Can you show me what the code looks like after you made the change?  It seems to be working if I just hardcode in a set value but that isn't going to work across the different themes.

**Comment by vasqued2** [comment]
It appears that not all themes define `ha-card-border-radius`.  It's working if I default to 10px if it's not defined, but I'd like to confirm it's picking up the value if it is.  Let me know what theme you are using and I'll confirm it's picking it up correctly.

**Comment by vasqued2** [comment]
I'm good.  I added `ha-card-border-radius` to my theme and it picked it up so if a theme defines it, it will use it.  If not, it will default to 10px, which appears to be what the default theme uses.

Thanks for you help w/ this.  I'll include the fix in the next release of the card.

**Comment by vasqued2** [comment]
Resolved in v0.6.0

**Comment by m1ke-hub** [comment]
Hey man, sorry for not responding earlier. Glad, you got that working without my answer! Just updated to the newest version - it's working perfectly!! 👍
Thank you so much for your work and have a wunderful christmas!
