### ISSUE TITLE
Templating Issues on v0.6.0

### ISSUE THREAD

**Issue by brandoningli** [vasqued2/ha-teamtracker-card#32]
Instead of the text "Today" and "Tomorrow", I'm seeing `{common.today}` and `{common.tomorrow}`

HA 2022.12.8
TT integration 0.6.0

**Comment by vasqued2** [comment]
It's usually a caching issue.  Have you tried to clear the cache and refresh?  Someone else reported the same problem pre-release but I didn't get the details of their setup.  It seems like the language files aren't always being cleared when refreshing from HACS.  Are you using a browser or the app?  If app, Android or Apple?

**Comment by brandoningli** [comment]
Ah, clearing my app cache (Android 13) did the trick.
