### ISSUE TITLE
Day of the week issue

### ISSUE THREAD

**Issue by ex1n3** [vasqued2/ha-teamtracker-card#39]
Running v0.6.1 for both the Team Tracker integration and card frontend. Home assistant 2023.1.1, but this has been happening since 2022.11.

Pretty standard card setup --

type: custom:teamtracker-card
entity: sensor.team_tracker
home_side: left
show_rank: true

Shows the below where the day of the week should be.
![Capture](https://user-images.githubusercontent.com/85259635/211042875-6a4eb875-3178-4ea1-bccd-6a5614bef675.JPG)

**Comment by vasqued2** [comment]
For some reason, the cache isn't getting completely refreshed on at least some Android platforms for the latest card upgrade. 
 Assuming you are using the app, try clearing your cache and restarting the app.  If using a browser, clear the cache and refresh the page.

Lmk if that doesn't resolve it and we can look more at your specifics.

**Comment by ex1n3** [comment]
Using a browser, but clearing the cache did the trick! Thanks.
