### ISSUE TITLE
Lovelace card not showing up in card selection

### ISSUE THREAD

**Issue by screwzloose** [vasqued2/ha-teamtracker-card#4]
Running into an issue where the Team Tracker Card is not showing up as an available lovelace card in the Add Card page.

1. Installed the Team Tracker Card into Lovelace via the current repo. 

2. Added to the configuration.yaml:
```
url: /hacsfiles/ha-teamtracker-card/ha-teamtracker-card.js
type: module
```
I will note, Type has to be set to "module" and not "Javascript Module" otherwise HA will spit out the following error:

```
`The system cannot restart because the configuration is not valid: Invalid config for [lovelace]: value must be one of ['css', 'html', 'js', 'module'] for dictionary value @ data['lovelace']['resources'][1]['type']. Got 'Javascript Module'. (See /config/configuration.yaml, line 4).
```

3. Restarted HA

5. Attempted to Add Card via the card selection, but the card does not exist. 

6. Multiple restarts, removed/replaced the Team Tracker Card from the Frontend in HACS. Still not showing up.

Using:
Hacs 1.27.2
Frontend version: 20220906112053

Home Assistant 2022.9.5
Supervisor 2022.09.1
Operating System 9.0
Frontend 20220907.2 - latest

**Comment by vasqued2** [comment]
It looks like you are confusing several different things.  I'll try to walk you through it.  First, did you install via HACS or did you install manually?

**Comment by screwzloose** [comment]
Ugh, if I'm n00bing it up and wasting your time, my apologies. I hope not.

I have Team Tracker Card installed via HACS. (HACS > Frontend > Team Tracker Card (Lovelace)).

I also Team Tracker (from your repo) installed via HA Integrations and have defined a team when I added to integrations.

**Comment by vasqued2** [comment]
No worries.  

If you installed the card via HACS, I think the README has some old info and you don't need to add the lines to your resources any more.

You can confirm by going to Settings/Dashboards, and then clicking on the three dots menu in the upper right.  If HACS added it, you should see it listed.  If not, click the Add Resource button on the bottom right and add the info.

If it was already added, please let me know and I will update the README to take that part out.

Then, assuming you have the sensor created from the integration (either through the UI or via YAML), you should just need to add the card to your Dashboard.

The card type teamtracker-card won't show up.  You have to select Type "Manual".  Then paste in the following where it asks you to type in your YAML.

```
type: 'custom:teamtracker-card'
entity: sensor.team_tracker
```
where sensor.team_tracker is whatever you called your sensor.

Let me know if you have problems and we can track it down.

**Comment by vasqued2** [comment]
Great news!  I'll clarify in the readme.

**Comment by vasqued2** [comment]
Updated the README to show that you do not need to add the Resources if adding via HACS and to make it clear you should add via a Manual card.
