### ISSUE TITLE
card in HA says common.tomorrow

### ISSUE THREAD

**Issue by Nusse469** [vasqued2/ha-teamtracker-card#42]
After a recent update whenever I have a game (basketball or football) coming up the next day, the card in Home Assistant has a "common.tomorrow" entry in the middle of it.

The card itself is set to "PRE" and worked here until one of the updates as I said. I have made zero changes between when it was and wasn't working.

It does not happen post game or when the game is more than a day away.

**Comment by vasqued2** [comment]
It's likely a caching problem.  Try clearing the cache and then either restarting the app if you are using an app or clearing the cache and then refreshing the page if in a browser.  For some reason, HA isn't refreshing the language files for upgrades and you have to manually clear the cache and refresh.

lmk if that works.

**Comment by Nusse469** [comment]
Yep that did it.  Thanks... easy fix.

**Comment by vasqued2** [comment]
Great.  Leaving open for others

**Comment by Jizzay1** [comment]
> Great. Leaving open for others

thanks for leaving open, helped me!

**Comment by vasqued2** [comment]
Assumed everyone had upgraded by now.  Closing
