### ISSUE TITLE
Request: add ability to define pre/current/post games

### ISSUE THREAD

**Issue by timknowlden** [vasqued2/ha-teamtracker-card#43]
Hi. Just added my team Norwich as a custom API. I would like to show 3 cards on my dashboard, past game, current game and next game. The default tracker card doesn't seem to have a way to define which fixture to show? 

This game took place yesterday for reference.
![Screenshot_20230115_183701_Home Assistant](https://user-images.githubusercontent.com/73787006/212560334-1d63aaa2-8b1f-4826-be11-6c843bb60de4.jpg)

**Comment by timknowlden** [comment]
Just to add.. I assume images are pulled from espn too? They have the wrong crest as norwich updated their one last year.

**Comment by vasqued2** [comment]
Both the image and the game info is returned by the API.  I can't control either.  The card displays whatever ESPN returns.

I will note that some images are out-of-date in the Wiki on the [Known ESPN Issues page](https://github.com/vasqued2/ha-teamtracker/wiki/Known-Defects-in-the-ESPN-API).

If you want to display info on past or upcoming games, you can look into using Google Calendar as described [here](https://smarthomepursuits.com/teamtracker-integration-home-assistant-real-time-sports-scores/).

**Comment by timknowlden** [comment]
Thanks for the info, I understand how it works now. I already gave google calendar integrated for scheduled games. And will incorporate this too. I have an iframe showing last game score but that isn't pretty. I also have an iframe with league table but would love it if this team tracker could show the league table at some point or all scheduled league fixtures for that day.
