### ISSUE TITLE
"Repository 'vasqued2/ha-teamtracker-card' exists in the store."

### ISSUE THREAD

**Issue by mgreez** [vasqued2/ha-teamtracker-card#44]
I am receiving an error that says the integration exists in the store, but it does not... any thoughts?

![image](https://user-images.githubusercontent.com/75751701/213026408-c719539f-5e7f-43f7-abd8-5aa6761ce7b8.png)

**Comment by vasqued2** [comment]
Can you find and install other cards and this issue is only with this one or with all cards?

**Comment by vasqued2** [comment]
What happens if you click on this link?

[https://my.home-assistant.io/redirect/hacs_repository/?owner=vasqued2&repository=ha-teamtracker-card&category=frontend
](https://my.home-assistant.io/redirect/hacs_repository/?owner=vasqued2&repository=ha-teamtracker-card&category=frontend
)

**Comment by vasqued2** [comment]
Added button to directly install card in README.  

Assuming issue is resolved due to no response.

**Comment by mgreez** [comment]
> What happens if you click on this link?
> 
> [https://my.home-assistant.io/redirect/hacs_repository/?owner=vasqued2&repository=ha-teamtracker-card&category=frontend ](https://my.home-assistant.io/redirect/hacs_repository/?owner=vasqued2&repository=ha-teamtracker-card&category=frontend)

Works perfectly!  Thank you, David
