### ISSUE TITLE
was working fine. now it says Custome element doesn't exist: teamtracker-card

### ISSUE THREAD

**Issue by Menz01** [vasqued2/ha-teamtracker-card#45]
i have had this card on my dashboard for a bit with no issues. now, when i go to my dashboard i see:

![image](https://user-images.githubusercontent.com/31291495/213569486-271c4dde-06b3-4a87-b5cc-171caa5331b7.png)

the only thing i remember doing is updating HA

**Comment by vasqued2** [comment]
You get this error when you delete or rename the card.  Try re-installing from HACS.  Or re-downloading if it looks like it's already installed.

**Comment by Menz01** [comment]
I tried the "redownload" in HACS and it didn't work. Still same error

**Comment by Menz01** [comment]
i deleted the team tracker card from HACS, restarted, added it back. restarted and it still shows the same error

**Comment by vasqued2** [comment]
Check and make sure it’s installed correctly by making sure you have a file called `ha-teamtracker-card.js` in the following directory:

`config/www/community/ha-teamtracker-card`

Then make sure you have something like the following in your resources with type JavaScript module:

`/hacsfiles/ha-teamtracker-card/ha-teamtracker-card.js`

**Comment by Menz01** [comment]
> Check and make sure it’s installed correctly by making sure you have a file called `ha-teamtracker-card.js` in the following directory:
> 
> `config/www/community/ha-teamtracker-card`
> 
> Then make sure you have something like the following in your resources with type JavaScript module:
> 
> `/hacsfiles/ha-teamtracker-card/ha-teamtracker-card.js`

i definitely have the first..
![image](https://user-images.githubusercontent.com/31291495/213594425-921a780a-0deb-429b-9811-0208dcbd12bc.png)

i dont know where to look for the second one

**Comment by vasqued2** [comment]
Settings, Dashboard, then select Resources from the three dots menu in the upper right.

**Comment by Menz01** [comment]
rebooted the VM and now its working again.... very weird

**Comment by vasqued2** [comment]
Very strange.  Thanks for the update.
