### ISSUE TITLE
Feature request - Swedish hockey league

### ISSUE THREAD

**Issue by DanielGoransson1** [vasqued2/ha-teamtracker-card#49]
Hi,

Great card, would be great with the teams from the Swedish hockey League. Is it possible?

**Comment by vasqued2** [comment]
Doesn't look like it.

Here are the list of known supported hockey leagues:
[http://sports.core.api.espn.com/v2/sports/hockey/leagues?lang=en&region=us](http://sports.core.api.espn.com/v2/sports/hockey/leagues?lang=en&region=us)

SHL isn't listed and didn't work.  You can try other values and see if they work but chances are probably low.
