### ISSUE TITLE
desaparecen las targetas

### ISSUE THREAD

**Issue by ancvalencia** [vasqued2/ha-teamtracker-card#50]
al cabo del tiempo desaparecen las targetas y hay que desinstalar team tracker card y volverlo a instalar para que se muestre las targetas otra vez esto pasa desde hace tiempo

**Comment by vasqued2** [comment]
que quieres decir con "desaparecen "

"Custom element doesn't exist" error o algo más

**Comment by ancvalencia** [comment]
me sale este error y perdon si no me explique bien,  "Custom element doesn't exist error ". esto aque se debe? estoy haciendo algo mal? necesito algo de ayuda gracias

**Comment by vasqued2** [comment]
A veces lo veo cuando reinicio.  Pero no es necesario reinstalar.  Simplemente actualice el navegador o reinicie la aplicación.  
Intentalo.
