### ISSUE TITLE
Feature Request - Custom Name

### ISSUE THREAD

**Issue by jgeorge1983** [vasqued2/ha-teamtracker-card#57]
Is it possible to have an option to add a custom name to custom leagues?

For international soccer for instance I have the FA Cup, but i set it up with XXX, so it would be good if I could set the "show league" to a custom name.

Thanks,

**Comment by vasqued2** [comment]
Use card_title in the card configuration.
```
card_title:  FA Cup
```

**Comment by jgeorge1983** [comment]
awesome, I didn't see that in the options.  my bad
