### ISSUE TITLE
Delayed score display

### ISSUE THREAD

**Issue by olgru** [vasqued2/ha-teamtracker-card#63]
A real great card! I'm using it as conditional display for my favorite teams. There is just one thing whch would make this card nearly perfect!
Being in Europe, the US-Sport games happen often in night time. While I record them or use Gamepass for viewing later, unfortunately the result is already displayed in the card. I prefer not to know them when I watch...

So, here's my feature request:
A score display delay option! For instance - delay display of final score for 1-48 hours.

**Comment by vasqued2** [comment]
You should be able to do this using a Conditional Card.  [Here is a Wiki entry](https://github.com/vasqued2/ha-teamtracker/wiki/Using-Conditional-Cards-to-Hide-NOT_FOUND-Status) that shows how to use the Conditional Card to hide the card if the status is `NOT_FOUND`.  You would just want to hide the card if the state was `POST` and potentially add a second condition based on the start time of the event.

If you really wanted to get tricky, you could use the Conditional Card in combination with card-mod as described in [this Wiki entry](https://github.com/vasqued2/ha-teamtracker/wiki/Using-CARD-MOD-card-to-format-the-TEAMTRACKER-CARD) to hide only the scores on the card and use the Conditional Card to show either the card-mod version or the unmodded version based on how long after the event it is.

**Comment by vasqued2** [comment]
Closing as I will not be making changes to support this natively as it can be done w/ by using other HA cards in combination with this one.
