### ISSUE TITLE
Missing info on card

### ISSUE THREAD

**Issue by PHI34Halladay** [vasqued2/ha-teamtracker-card#67]
Hi, I was wondering, why I'm not getting the last play info which is on various Screenshots plus the win probability is always at 0/0%..

![Screenshot_20231123-191538](https://github.com/vasqued2/ha-teamtracker-card/assets/46962608/a7decc1e-63c8-4eb3-a8e6-8b762e3b16b5)

Any tips?

**Comment by vasqued2** [comment]
Just has someone report a similar issue w/ German localization.  What language are you using?  I'll watch during the next games and see if I can figure out what is going on.

**Comment by PHI34Halladay** [comment]
I'm using german language right now.

How can I change that completely?

**Comment by vasqued2** [comment]
The language is based on the language of your front end.  You should be able to change it by going into your Profil and selecting English.

But I just changed my language to German and I am still getting the stats, etc. for the Miami/NY Jets game going on now.  So it may not be related to your language being German.  I'll keep digging.  You might want to try creating a sensor for MIA to see if that works for you or you still have the problem.

**Comment by PHI34Halladay** [comment]
It worked for me tho..

I had to set my profile to English but also the country and the language under system/general
![Screenshot_20231124-224912](https://github.com/vasqued2/ha-teamtracker-card/assets/46962608/0330d88f-fd6c-40f2-a4ca-4d13580fb1ac)

**Comment by vasqued2** [comment]
I've just confirmed the API isn't returning the play-by-play details when it returns the German translation.  There is nothing I can do to get it added in German.  My guess is because ESPN doesn't translate that to German.  I know for some languages, if there is not trasnlation, it just returns English but that doesn't seem to be the case for German.  Sorry.

**Comment by PHI34Halladay** [comment]
Is there any chance to prevent everything getting translated?

Yes I want to have my homeassistant set up in german, but I don't need the info from teamtracker to be translated into German language.

**Comment by vasqued2** [comment]
I might be able to add something that will allow it to override the HA language and force it to use English.  I'll have to think about how.  I'll leave this open until I decide what to do.

**Comment by PHI34Halladay** [comment]
Ok, thanks.

**Comment by PHI34Halladay** [comment]
Just wanted to let you know, that the language problem is no more for me.
I changed the whole HA-language to english and then back to german and now I still get the complete infos on the card.

**Comment by vasqued2** [comment]
That is just strange.  I will be working on a way to force an API language in an upcoming release.  There are enough bizarre behaviors that I think it could be of value to someone.

**Comment by vasqued2** [comment]
If you upgrade to v0.11.0 for both the sensor and the card, you can use the new `api_language` configuration option to override your local language an use whatever you want (i.e. `en`).  If you set up the sensor via the UI, you can set it via the Configuration option UI for the sensor.
