### ISSUE TITLE
Home Team/Team time out display incorrectly for your team

### ISSUE THREAD

**Issue by rellerton** [vasqued2/ha-teamtracker-card#68]
The team time outs for the selected teams show as blank for NFL. I'm currently tracking three teams and while all three teams are in the In position they always show as their time out's being blank, while the opponent shows correctly. I assume the issue is with the card as the underlying metadata in Home Assistant appears to show the correct number of time outs.

**Comment by vasqued2** [comment]
I finally had a chance to track this during a live game today and it is working for me with the home team showing on either side.  If you are still having a problem, can you give me more specifics on your setup?  Maybe using a different language other than English?  If you can get a screen shot of the card and the sensor values, that would also help.  Timeouts work inconsistently in other sports, but I've never seen ad a problem w/ the NFL.

Thanks!

![image](https://github.com/vasqued2/ha-teamtracker-card/assets/17114183/b99d7b8f-ab93-4285-ba86-a606ec0918e6)

**Comment by rellerton** [comment]
My team is playing tomorrow and I set a reminder to check it. Definitely saw it in three different games. I'm pretty sure I also saw an example of it watching college ball, but my team is out - FSU, we won't go there - but I'll check tomorrow to be sure. My setup is as basic as it can be. I have two teams monitored - Tampa Bay and FSU, the card configurations look like this. One thing I didn't think about was that I nested them in a vertical-stack card with custom CSS, which could definitely mess with the CSS of the cards - if I can reproduce it tomorrow I'll create a standalone card and see if it behaves the same way.


```
type: vertical-stack
cards:
  - type: markdown
    content: |
      # Football
    style:
      .: |
        ha-card {
          background-color: transparent !important;
          box-shadow: none !important;
          border-width: 0px !important;
        }
      ha-markdown:
        $: |
          h1 {
            font-size: 25px;
           # font-weight: bold;
            text-align: center;
            letter-spacing: '-0.01em';
          }
  - type: custom:teamtracker-card
    entity: sensor.team_tracker_tampa
  - type: custom:teamtracker-card
    entity: sensor.team_tracker_fsu
```

**Comment by vasqued2** [comment]
There used to be a problem w/ the ESPN API for timeouts for College Football and it always returned 3 and never updated throughout the game.   I assume that is still the case but wouldn't swear to it.  NFL should be working though

**Comment by vasqued2** [comment]
It worked for me for the NFL games this weekend.  If you are still having problems w/ NFL games, please reopen and provide more details.  Again, timeouts for NCAAF games are not updated by the API.
