### ISSUE TITLE
ha-teamtracker-card fails to load

### ISSUE THREAD

**Issue by ejpenney** [vasqued2/ha-teamtracker-card#69]
Hi,

Amazon Fire tablet 10 is getting an error today:

`Custom element doesn't exist: teamtracker-card`

I'm only seeing this issue on one device, running the debugger I see:

```
cdn.jsdelivr.net/gh/lit/dist@2/core/lit-core.min.js:1 
        
Failed to load resource: net::ERR_CONNECTION_REFUSED
```

The only thing unique I'm aware of with this device is it's an Amazon Tablet, running webview version: `116.amazon-webview-v116-5845-tablet.5845.229.65`

I've tried clearing cache, restarting, re-insatlling, etc.

**Comment by arychj** [comment]
@ejpenney I don't know if you're using a network blocker, but `cdn.jsdelivr.net` got added to a block list on my pihole for some reason. I added an exception for it and the card works again.

**Comment by ejpenney** [comment]
Well, that's embarrassing. I saw 3 other devices worked and so I didn't bother to check the PiHole. You're correct, whitelisting that domain fixed it! I guess the Fire tablet doesn't cache as aggressively as all the others.
