### ISSUE TITLE
HA Shows teamtracker-card Not found

### ISSUE THREAD

**Issue by BeSt1979** [vasqued2/ha-teamtracker-card#82]
In my HA with
Core
2024.5.0
Supervisor
2024.04.4
Operating System
12.2
Frontend
20240501.0

it shows: custom element teamtracker-card Not found, although correctly installed.

**Comment by vasqued2** [comment]
Have you tried clearing your cache and refreshing?  If you can, check the developer console in the browser and see what errors are being displayed.
