### ISSUE TITLE
Custom element doesn't exist - fire tablet 2021

### ISSUE THREAD

**Issue by addrum** [vasqued2/ha-teamtracker-card#83]
Have this card working fine on the newest iPad mini and an iPhone 13 Pro, but currently shows "custom element does not exist" on an Amazon fire tablet running Android 9, web view 	120.0.6099.266.

Home assistant is running docker on version 2024.5.3.

Tracker integration v0.11.1
Card version v0.11.1

Let me know if this is just because the tablet is a bit old, it's no bother but would be cool to have it working!

**Comment by vasqued2** [comment]
Try clearing the cache and reloading.  Also, if you can see the developer console in the browser, see if there are any error messages.  If so, post them here.  I don't have a fire tablet so I won't be able to reproduce it.

**Comment by addrum** [comment]
Yeah have tried clear the cache and a complete reboot too. Will try and get console logs for you!
Forgot to mention this is running in Fully Kiosk browser so will also check the native web browser too.

**Comment by vasqued2** [comment]
This is based on the ha-nfl-card.  It looks like someone was having problems w/ it in kiosk mode too and it doesn't look like it was ever resolved.  Not the best sign.  

https://github.com/D34DC3N73R/ha-nfl-card/issues/3

But there is someone who got it to work in kiosk mode.

https://github.com/vasqued2/ha-teamtracker-card/issues/34

**Comment by addrum** [comment]
Solved. The tablet was behind a firewall that was blocking the JavaScript files and espn's cdn. Allowed those and cache refreshed and now working! Thanks for the help!
