### ISSUE TITLE
Feature Actions

### ISSUE THREAD

**Issue by milandzuris** [vasqued2/ha-teamtracker-card#88]
Hi please add feature when i click on Card open the Entity.

```
tap_action:
  action: ***
hold_action:
  action: **
double_tap_action:
  action: ***
```

**Comment by vasqued2** [comment]
Can you give me more specifics.  Do you want to click on different components of the card to have different things happen?  If so, what type of things?  Links to other sites, HA actions, etc?  Or do you want different things to happen on different actions like you describe?  Give me examples of the actions.

**Comment by milandzuris** [comment]
> I am leaning towards creating 3 hot spots. One on each team icon and one at the bottom. By default they will link to each team page and the game page on ESPN but will allow each url to be overwritten in the card config.

this sounds amazing, and add HA actions.

**Comment by vasqued2** [comment]
I am not sure I understand by what you mean by HA actions.  Can you share a card that has the capability so I can take a look at it?

**Comment by milandzuris** [comment]
> I am not sure I understand by what you mean by HA actions. Can you share a card that has the capability so I can take a look at it?

https://www.home-assistant.io/dashboards/actions/

**Comment by vasqued2** [comment]
Tap actions look like they are only available on some native HA components.  I can't find any custom cards that have implemented them and I don't see any way for a custom card to easily leverage the HA implementation.

With that said, the only action I see that makes sense to me is a hot link to a url, which I can implement.  Maybe I don't understand what all the actions are.  Were you thinking of another action you wanted to take on a tap other than to navigate somewhere?

**Comment by milandzuris** [comment]
> Tap actions look like they are only available on some native HA components. I can't find any custom cards that have implemented them and I don't see any way for a custom card to easily leverage the HA implementation.

https://github.com/maxwroc/battery-state-card?tab=readme-ov-file#tap-action

**Comment by vasqued2** [comment]
I see.  Thanks. They used TypeScript to implement it.  That card is written in Javascript so it would require a full rewrite to incorporate the code in some fashion and I'm not familiar with TypeScript.  

For now, the new version will implement HTML hotspots and allow the default URLs to be overwritten in the card config.  I should be able to release a beta version later today for you to try.

If you want to submit a pull request to implement the other actions, I'll take a look at it.

**Comment by vasqued2** [comment]
You should be able to download beta versions of v0.14.0 for the card and the sensor.  Let me know if it works as you expected.

By default, it will populate the team and event URLs if they are provided by the API.  You can overwrite them by including different URLs in the card configuration.

```
home_url: https://www.espn.com
opponent_url:  https://www.ticketmaster.com
bottom_url:  https://www.nfl.com
```

**Comment by milandzuris** [comment]
> home_url: https://www.espn.com
> opponent_url:  https://www.ticketmaster.com
> bottom_url:  https://www.nfl.com

not working, and question why when is entity defined (entity:) and i click on card not open entity?
![image](https://github.com/vasqued2/ha-teamtracker-card/assets/42905545/de6678dc-8278-4044-94f5-e2b9084a5b3f)

**Comment by vasqued2** [comment]
Buday isn't listed as fighting on 7/13.  That is why nothing is found and the links are not active when the status is NOT_FOUND.
 
If you had a sensor for FREMD is should work because he is fighting in the upcoming event.

**Comment by vasqued2** [comment]
I might be able to trigger tap actions, however it looks like they won't be user configurable from the card.  If so, what actions would you want and how would you want them triggered.  My inclination is to keep the 3 hotspots that I already have an enable more-info with a double-click.  I would not enable service calls and toggle/assist doesn't make any sense.

Lmk what you think.

**Comment by vasqued2** [comment]
I was able to get the more-info working on a double-click in areas that are not already a hotspot for a single click (i.e. the middle of the card where the score is).  Lmk if this is what you are thinking and I will re-release a new beta.

**Comment by vasqued2** [comment]
Published this functionality as beta2 if you want to test.

I will be unavailable for the next week and plan to release after that unless there is additional feedback.

**Comment by vasqued2** [comment]
This feature was added in v0.14.0.  It requires v0.14.0 of the team tracker sensor as well.

**Comment by ClaymoreTech4** [comment]
FYI the URL Actions do not work in Chrome Version 127.0.6533.89 (Official Build) (64-bit), Home Assistant IOS or Android App.  This does work in Microsoft Edge

**Comment by vasqued2** [comment]
You likely need to clear your cache and refresh to pick up version v0.14.1 even if you installed it from HACS.  You can also check the version in the Chrome Console under DevTools.  If you have a lower version, it won't work.  

Lmk if you still have problems after confirming you are picking up the current version.  I have the same version of Chrome and it's working for me so you are probably just picking up the wrong version.

**Comment by ClaymoreTech4** [comment]
Thank you, Fixed
