### ISSUE TITLE
card does not work

### ISSUE THREAD

**Issue by bpwats** [vasqued2/ha-teamtracker-card#93]
Installed manually (all steps), automatically through HACS does not work:

Repository vasqued2/ha-teamtracker-card not found

card is not found/shown

**Comment by vasqued2** [comment]
To be clear, you installed manually and then reinstalled via HACS?

First try clearing your cache and refreshing.

If it still doesn't work, check your Resources and make sure `/hacsfiles/ha-teamtracker-card/ha-teamtracker-card.js` is in the list.

If it still doesn't work, provide more specifics on app or browser used, etc.

**Comment by vasqued2** [comment]
Closing due to non-response.

**Comment by bpwats** [comment]
@vasqued2 figured it out: set HACS filtering to ALL (instead of NL in which case it cannot be found)
