### ISSUE TITLE
[Feature request] - Option to overwrite url of team logo

### ISSUE THREAD

**Issue by NilsAla** [vasqued2/ha-teamtracker-card#94]
Hello,
Thank you very much for your work on this card. Just installed and it works flawless! Unfortunately has ESPN no logo of my team on their website and I only see a placeholder instead of the logo on the card :( 

![Screenshot_2024-08-04-13-46-30-22_64ef5fc2000c1caa954c114bb372e1d5](https://github.com/user-attachments/assets/f65185d9-a515-4c87-b8b3-a6dd7367039d)

I checked the team tracker API response in the entity and the "team_logo"-attribute is empty. I tried to overwrite the attribute directly in the entity but wasn't able to because it gets overwritten with every new API-request. 

I know that this is not really a huge issue but I thought I try my luck and ask you if it would be possible to add another option to this card to overwrite the team_logo attribute with a custom link like the the team_url option. I have no real experience with coding and don't know how much work this is to add such a feature. If this is complicated and time consuming I can totally understand if this issue gets rejected 😅

Thanks!

**Comment by vasqued2** [comment]
Looks like it's working now.  Looks like it could have taken ESPN a while to get their logo loaded after promotion?  Let me know if you are still having problems.

![image](https://github.com/user-attachments/assets/6e17310c-c124-4872-aaec-46103fd416e8)

**Comment by NilsAla** [comment]
Oh yeah, thanks for the info!
They probably added the logo in the last days :)
