### ISSUE TITLE
[Feature request] option to disable TV-Network, odds and overunder

### ISSUE THREAD

**Issue by TheGlorySaint** [vasqued2/ha-teamtracker-card#96]
Hi @vasqued2,

nice integration.

I'd like to disable the TV-Network, odds and overunder. For me these are not necessary. Instead, where the odds, tv-network and overunder are, I want to have there the Stadium and city where the event is.

Would it be possible to add bool's where you can disable or enable these UI elements and position them?
Is it possible to add the Date of the Game, where for example currently the TV-Network Attribute is?

Sadly, I can't write any .JS, so it is impossible for me to modify it myself.

**Comment by vasqued2** [comment]
The card should be fully compatible with [card-mod](https://github.com/thomasloven/lovelace-card-mod), which should let you do everything you are trying to do.

In fact, there are examples in the [card-mod page](https://github.com/vasqued2/ha-teamtracker/wiki/Using-CARD-MOD-card-to-format-the-TEAMTRACKER-CARD) in the Team Tracker Wiki that do pretty much what you are trying to do.  If you have problems or find an element that isn't identifiable via a class name, lmk.

Card-mod provides so many customization possibilities that it made more sense to make the card compatible with it than to try to make even half of those options configurable.  Everyone wants to do something different.  Card-mod allows that.

And don't sell yourself short.  If you look at the `render_` files it would take you about 2 seconds to figure out how to make the changes to reorg the card yourself.  Of course you'd have to remake them every upgrade, which is the benefit of card-mod.

**Comment by TheGlorySaint** [comment]
Hi @vasqued2,


Thanks for your reply.

I looked at the render_pre.js file and changed the odds class name in pre-row1 to "gamedate" and as value i changed from `${c.pre1}` to `${c.gameDatePRE}`. After that, I restarted Home Assistant, but this did not change the style of the Card.

Working with CSS to hide the `.odds, .network, . overunder` did work. But at best, I work in the render_pre.js file, to make my adjustments.

**Comment by vasqued2** [comment]
First, if there are any zip/gz files in the folder, delete them,  They will override any change you made to the js files.  You can always redownload everything in HACS if you want.  Or you can rename them to a different suffix.

second, in your browser or app you are using to view the cards, clear the cache then refresh the page so you pick up the new version instead of using the old cached version..

**Comment by vasqued2** [comment]
Closing due to no follow-up
